version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: classicmodels-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classicmodels
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_URL: http://localhost:4000/api
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  mysql_data:
